[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  adafruit/Adafruit SHT4x Library@^1.0.5
